services:
  postgres:
    image: postgres:17-alpine
    container_name: task1-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analysis_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tasknet

  redis:
    image: redis:7-alpine
    container_name: task1-redis
    ports:
      - "6379:6379"
    networks:
      - tasknet

  app:
    build: .
    container_name: task1-app
    command: npm run dev
    environment:
      # DATABASE_URL: postgres://postgres:postgres@localhost:5432/analysis_app
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/analysis_app
      CHROME_PATH: /usr/bin/chromium
      REDIS_URL: redis://redis:6379
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - tasknet

networks:
  tasknet:

volumes:
  pgdata:
